#!groovy

// Generated by IBM TransformationAdvisor
// Wed Jan 23 16:15:08 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}